Refactored Perceptionhash for performance
corona10/goimagehash pull request #54
Opened 2022-05-12 04:30 UTC by evanoberholster

Refactored PerceptionHash for performance.
- Significantly reduces allocations
- Uses static DCT1D tables
- Uses sync pool to reduce pixel data allocations
- Uses image.Image optimizations for obtaining pixels for improved inlining of functions
- Backward compatible with PerceptionHash, they are interchangeable. Confirmed with passing tests.
- Performance without image resize as below.
```go
PerceptionHash/Regular-12         358µs ±26%
PerceptionHash/Fast-12           84.8µs ± 7%
PerceptionHash/Parallel-12       82.5µs ± 3%
PerceptionHash/Fast-Parallel-12  11.5µs ± 1%

name                      alloc/op
PerceptionHash/Regular-12         193kB ± 0%
PerceptionHash/Fast-12            17.0B ± 0%
PerceptionHash/Parallel-12        193kB ± 0%
PerceptionHash/Fast-Parallel-12    198B ± 0%

name                      allocs/op
PerceptionHash/Regular-12         4.68k ± 0%
PerceptionHash/Fast-12             0.00     
PerceptionHash/Parallel-12        4.68k ± 0%
PerceptionHash/Fast-Parallel-12    0.00 
```

2022-05-12 05:23 UTC, evanoberholster commented
Comparison between PerceptionHash and PerceptionHashFast:
```go
name               old time/op    new time/op    delta
PerceptionHash-12     945µs ± 9%     689µs ± 2%  -27.08%  (p=0.000 n=170+177)

name               old alloc/op   new alloc/op   delta
PerceptionHash-12     471kB ± 0%     298kB ± 0%  -36.80%  (p=0.000 n=174+198)

name               old allocs/op  new allocs/op  delta
PerceptionHash-12     4.74k ± 0%     0.07k ± 0%  -98.61%  (p=0.000 n=200+200)
```

2022-05-12 15:05 UTC, corona10 requested changes
@evanoberholster Looks nice! Thank you for your contribution!!

>  If you want me to change the name to replace existing function that would be acceptable.

I prefer this one(change the name ) :)

2022-05-12 15:09 UTC, corona10 commented
Please add your name to the following file.
https://github.com/corona10/goimagehash/blob/master/AUTHORS.md

2022-05-12 15:14 UTC, corona10 commented
> Significantly reduces allocations
> Uses static DCT1D tables
> Uses sync pool to reduce pixel data allocations
> Uses image.Image optimizations for obtaining pixels for improved inlining of functions
> Backward compatible with PerceptionHash, they are interchangeable. Confirmed with passing tests.
> Performance without image resize as below.

Thanks, I love all of your changes :)

2022-05-12 23:46 UTC, corona10 requested changes
Would you like to switch the PerceptionHashFast into PerceptionHash and remove old implementation?

2022-05-12 23:46 UTC, corona10 commented on hashcompute.go
> +func PerceptionHashFast(img image.Image) (*ImageHash, error) {
```suggestion
func PerceptionHash(img image.Image) (*ImageHash, error) {
```

2022-05-15 12:29 UTC, evanoberholster commented
PerceptionHashFast DCT static tables only support a size of 64x64. We would need to include further static tables to support other image sizes, (eg 256x256)

2022-05-15 12:58 UTC, corona10 commented
@evanoberholster 

> PerceptionHashFast DCT static tables only support a size of 64x64.

Ah okay, let's replace PerceptionHash only.

2022-05-18 02:06 UTC, evanoberholster commented
Sorry for the delay I have been busy at work. Will get it replaced and update the PR.

2022-05-19 07:34 UTC, corona10 commented
> Sorry for the delay I have been busy at work. Will get it replaced and update the PR.

Yeah, Don't worry I can wait :)

2022-05-25 04:19 UTC, evanoberholster commented on hashcompute.go
> +func PerceptionHashFast(img image.Image) (*ImageHash, error) {
Made these changes in new update.

2022-05-25 07:04 UTC, corona10 requested changes
Almost looks good to me, Just 1 nit comment and I will take a look at more later :)
Thanks for the change!

2022-05-25 07:04 UTC, corona10 commented on hashcompute_test.go
> +
IMHO, we can remove this test since `TestHashCompute` already covers this area.

```suggestion
```

2022-05-26 02:28 UTC, evanoberholster commented
I agree that those tests are redundant. Thanks.

2022-05-26 06:31 UTC, corona10 approved these changes

2022-05-26 06:32 UTC, corona10 commented on hashcompute_test.go
> +	"github.com/nfnt/resize"
```suggestion

```

Should be removed :)

2022-05-26 06:56 UTC, merged